services:
  mcp-mediawiki:
    image: mcp-mediawiki:latest
    build: .
    restart: unless-stopped
    ports:
      - "3000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      mcp_network:
        ipv4_address: 192.168.170.2

networks:
  mcp_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.170.0/24
          gateway: 192.168.170.1
